# Generated by Django 5.0.7 on 2024-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
