# Generated by Django 5.0.7 on 2024-08-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connectionrequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='receiver_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='sender_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
