# Generated by Django 5.0.7 on 2024-08-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_ongoingconnection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OngoingConnection',
        ),
    ]
