# Generated by Django 5.0.7 on 2024-07-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_date_of_birth_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
