# Generated by Django 5.0.7 on 2024-08-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='user',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
