# Generated by Django 5.0.7 on 2024-08-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_timeslot_user_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timeslots',
        ),
    ]
