# Generated by Django 5.0.7 on 2024-08-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_days_user_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timeslots',
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
